### ISSUE TITLE
https Drupal session cookie starts with 'SSESS' instead of 'SESS'

### ISSUE THREAD

**Issue by JesseKlaasse** [datagovuk/ckanext-dgu#115]
The Drupal<->CKAN authentication mechanism currently doesn't work correctly when Drupal is on a https link.

Two fixes are needed for this to work.
First, in /ckanext-dgu/ckanext/dgu/authentication/drupal_auth.py, the code needs to be as follows:

    if cookie.startswith('SESS') or cookie.startswith('SSESS'):
        # Drupal 6 uses md5, Drupal 7 uses sha256
        server_hash = hashlib.sha256(server_name).hexdigest()[:32]
        if cookie == 'SSESS%s' % server_hash:
            log.debug('Drupal cookie found for server request %s', server_name)
            return cookies[cookie].value
        elif cookie == 'SESS%s' % server_hash:
            log.debug('Drupal cookie found for server request %s', server_name)
            return cookies[cookie].value
        else:
            similar_cookies.append(cookie)

Furthermore, there is an issue in /ckanext-dgu/ckanext/dgu/drupalclient.py, for which I don't already know an elegant solution (which works for both http and https). In this line:

    xmlrpc_url_template = 'http://%s/services/xmlrpc'

For now, I have fixed this on our site by just replacing http with https here, but I'm looking for a solution which would work on both http and https.

**Comment by davidread** [comment]
@JesseKlaasse thanks for the tip. Do check my pull request and let me know.

And it would be great if you could send me an email with a bit of info about your CKAN project too, so that we know about users of Data.gov.uk To Go.

**Comment by davidread** [comment]
Assuming this is fixed ok for you.
