### ISSUE TITLE
Only first publisher page shows the number of datasets

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#140]
Past the first page it shows "0 datasets".

![dataset-total](https://cloud.githubusercontent.com/assets/3272/8660648/13c9043c-29aa-11e5-9720-2d032ae7e73f.png)

**Comment by davidread** [comment]
Link: http://data.gov.uk/publisher/health-and-social-care-information-centre?page=2

**Comment by davidread** [comment]
I'd suggest we simply replace the pager with a link to the main search page, filtered by this publisher. This could have label like "All datasets for this publisher".

**Comment by rossjones** [comment]
I'm not seeing this any more.  Each page shows the correct total for me. Can you close this if fixed please @morty

**Comment by morty** [comment]
Yes, this looks to have stopped now.
