### ISSUE TITLE
Zip data package

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#164]

**Comment by davidread** [comment]
http://redmine.dguteam.org.uk/issues/1890

**Comment by morty** [comment]
Nearly there, but there is an issue with IE, HTTPS and cache headers :(

**Comment by davidread** [comment]
Merged ckanext-dgu now (ckaenxt-archiver was merged and deployed before). You'll need to deploy: ckanext-dgu and ckanext-packagezip

**Comment by morty** [comment]
Deployed on live. Will take until after the weekend for all of the zip files to be created.
