### ISSUE TITLE
Convert User Guide to markdown

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#166]
- [x]    Publisher tools - create a MD page for the content on p11 and p12.
- [x]    Editing user permissions - create a MD page for p13
- [x]    Dataset form - update the existing MD page, section "Form fields guidance" to include p17-18, 20-25, 27-30.
- [x]    Reports - create based on p36
- [x]    Glossary - create based on p43-44
- [x]    FAQ - add to the existing one based on p46

**Comment by davidread** [comment]
http://redmine.dguteam.org.uk/issues/1839

**Comment by davidread** [comment]
https://github.com/datagovuk/guidance/pull/2/files

**Comment by davidread** [comment]
Nice work!

**Comment by morty** [comment]
OK, I've added a redirect from /guidance to guidance.data.gov.uk. Finally done done?

**Comment by davidread** [comment]
Great!
