### ISSUE TITLE
Remove cache_filepath extra

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#169]
Pull: datagovuk/ckanext-dgu#139

**Comment by rossjones** [comment]
Was just looking at this, and was a bit worried about removing 'openness_score' as it appears in several places still in the code (like indexing and the UKLP reports).  What is it replaced with? A direct lookup of QA data?

**Comment by davidread** [comment]
The extra value for openness_score is way out of date - we stopped updating
it a long while back. The data is now stored in the qa table.

We should probably add it back into the package_show result using an
after_show hook.

**Comment by rossjones** [comment]
as long as it doesn't break UKLP reports as I'd rather not fix them again :)

**Comment by rossjones** [comment]
This is running in a screen on prod2.

**Comment by rossjones** [comment]
Finished running on prod2. Seems to have worked.

**Comment by davidread** [comment]
Super, let's get it done on prod3 then

**Comment by davidread** [comment]
Tom to try it locally and run on live overnight
