### ISSUE TITLE
Change facets behaviour to gov.uk style

### ISSUE THREAD

**Issue by diabulos** [datagovuk/ckanext-dgu#177]
Similar behaviour to 
https://www.civilservicejobs.service.gov.uk/csr/index.cgi?SID=cGFnZWFjdGlvbj1zZWFyY2hieWNvbnRleHRpZCZ1c2Vyc2VhcmNoY29udGV4dD05NTE5MTc4JnBhZ2VjbGFzcz1Kb2JzJmtleT1mYWlyJnJlcXNpZz0xNDQzNTIzMjM4LTUyZmUwOWZiOTNmMThlMjUxYjcwYzIzZGQ0Zjc3OGYxNTU1Nzk1NDY=

**Comment by rossjones** [comment]
Can use either http://julesjanssen.github.io/chosen/ or https://select2.github.io/examples.html to do this (the latter looks nicer).

**Comment by rossjones** [comment]
This is happening in #315 so will close this as a dupe.
