### ISSUE TITLE
Change API icon to 'API'

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#179]

**Comment by rossjones** [comment]
I know it;s only a minor one, but change is in branch 179-api-not-icon

**Comment by davidread** [comment]
PR?

**Comment by rossjones** [comment]
Just wanted to see it first, need to move the styles out into the CSS I guess.

**Comment by davidread** [comment]
PR?

**Comment by davidread** [comment]
Is there no PR for this?

**Comment by rossjones** [comment]
No, it's not done.
