### ISSUE TITLE
Package zip link on dataset page

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#187]
(move from API tab)

**Comment by morty** [comment]
Is this something like it should look?

![datapackage](https://cloud.githubusercontent.com/assets/3272/10312615/d7145e88-6c43-11e5-9108-a1f3943e373d.png)

**Comment by diabulos** [comment]
Yes, although I wish we could change that badge layout, it is so unfriendly to click on the arrow, etc :-(

**Comment by rossjones** [comment]
Do you think putting nicely styled buttons in that box would be better than the dropdown? - I don't think anyone likes the dropdown really.

**Comment by morty** [comment]
After a few iterations:

![datapackage-box](https://cloud.githubusercontent.com/assets/3272/10314002/65e33af2-6c4a-11e5-92cf-11fac5eadde3.png)

The box on the right darkens like the others when hovered.

**Comment by diabulos** [comment]
very nice, maybe the icon should be a bit larger, in comparison to the blue, the tendency will be to click on the big one, unless the other option is large enough to break the dominance of the blue...

**Comment by davidread** [comment]
Yes much better.

How about we lose the "Download a copy of all of the cached resources for this dataset" and put that in hover text instead? People don't read sentences and it clutters things.

The package icon is already pretty big. How about we reduce the size of the normal resources down the page @diabulos ?

**Comment by morty** [comment]
Do we need to wire the packagezip download to a Google Analytics event?

Should it be the same one as for resource downloads or a new one?

**Comment by morty** [comment]
Deployed on prod2.

@davidread I'm not sure where you mean when you say put it in hover text - we don't seem to have any other hover text on that page.

**Comment by rossjones** [comment]
@morty check the cached option in the normal resource download, that has a hover.

I don't think it is so bad, and useful to have it clearly stated that it is cached, if we put it in a hover nobody'll see it and it'll just generate support issues (why is this file not the same as the source etc etc).

Looks good on test, perhaps the only thing I'd change is "Download all data" to "Download all data (98Mb)" so that it is clear how much they're getting.

**Comment by davidread** [comment]
In increasing the size of the download icon you've also increased the down arrow on all the other resources.

You may be right Ross about the sentence and confusion. Let's keep it in for now then and hide it in a few months when people are used to it.

Bonus if you can add the file size (maybe just for ones over 5MB?).

**Comment by davidread** [comment]
Great the zip on the dataset page looks good. Other tickets will deal with displaying the size and warning if zip empty.

**Comment by rossjones** [comment]
Merged and deployed to prod2.  Will deploy with 242

**Comment by rossjones** [comment]
This is blocked by https://github.com/datagovuk/ckanext-packagezip/issues/7

**Comment by rossjones** [comment]
What do we think of https://www.evernote.com/shard/s281/sh/0a42daea-8afd-4cbc-b9cf-f78ac9f45a0c/8492e626827191e8 (possibly with working changes) to show that the dataset doesn't have data (only the index.html/datapackage.json).

Any thoughts @davidread / @morty ?

**Comment by davidread** [comment]
Thanks for showing this. Yes it's difficult to express, but I think that it would be better in these cases not to show all the usual gubbins for the zip download. We're merely explaining to the eagle eye person why there isn't a zip for this dataset, so I think we still have the heading "Data Package" but then under it only a single line of text "Data Package Zip is not recommended for this dataset" then a question mark over which you can hover to get the detail you have. Also mention in that hover text that the data might only be available by API. You could still link to the zip, making "Data Package Zip" a link, if you hover.

**Comment by rossjones** [comment]
Pending deployment
