### ISSUE TITLE
Download of large datapackage zip files fails

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#188]
Gives an ugly Varnish 503 error when trying to download https://data.gov.uk/dataset/anonymised_mot_test/datepackage.zip which is 8Gb.

**Comment by rossjones** [comment]
We should definitely have prettier 50x pages - just in case, we could have nginx serve those couldn't we?

**Comment by diabulos** [comment]
Agree, some style, c'mon, a bit of elegance and humour would not go amiss on those. :-)

**Comment by rossjones** [comment]
I am quite partial to http://www.platinumgames.co.jp/404/

**Comment by diabulos** [comment]
Love this one for 404 https://www.google.co.uk/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAcQjRxqFQoTCID_1OCZrsgCFcPbGgod3PYHVQ&url=https%3A%2F%2Fwww.behance.net%2Fgallery%2F14371309%2F404-Site-Construction-Maintenance-Pages&bvm=bv.104317490,d.d2s&psig=AFQjCNHD-YuSVbUzozvtQLNAtnVOFItY7A&ust=1444233111807917

**Comment by diabulos** [comment]
I'll look into it

**Comment by rossjones** [comment]
The datapackages are seved via Nginx now (rather than via paster) so downloads are fine.
