### ISSUE TITLE
Show file size for a data-package

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#197]
Add a file size to the package zip link so users know how large the download is in advance.

**Comment by davidread** [comment]
(the warning issue is covered by: https://github.com/datagovuk/ckanext-packagezip/issues/7 )

**Comment by morty** [comment]
a7370c0 deployed on prod2 now

![zipfilesize](https://cloud.githubusercontent.com/assets/3272/10618615/d8382bb6-7768-11e5-9384-ec2b99d8e113.png)

There is a whole Megabyte, Mebibyte can of worms that I'd rather not go into. The Megabyte value reported is good, but won't match with the Firefox download window :(

**Comment by rossjones** [comment]
Closing this as now handled in #187
