### ISSUE TITLE
Nightly reports taking too long

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#202]

**Comment by rossjones** [comment]
Tom's first guess of "it's logging too much" does seem to be contributing too much to the problem.  Unless it is just accumulating over all the reports that are done it's not having a particular effect of speed of execution on my machine.

I think we need to know how long each one is 'supposed' to take, and work from there, but should also investigate how we sometimes end up with more than one instance (we should flock a file in cron) and where it appears to be getting stuck.

**Comment by davidread** [comment]
First rule of optimizing for speed is to get the numbers before you plan what to improve. Getting a run time for each report individually isn't hard to do (time paster report generate xyz) and will be a great start.

**Comment by rossjones** [comment]
Measuring is how I know it didn't make an improvement :)

**Comment by rossjones** [comment]
Finally finished running (apart from admin_editor which calls to Drupal and is raising 500 on my machine).

Times in seconds.

```
‘publisher-activity’: 6007.146883964539, => 1.6hrs
‘openness’: 1771.0450110435486 => 30mins
‘broken-links’: 693.9193770885468 => 10mins
‘unpublished’: 12.251199960708618 => 12s
‘nii’: 6.18639612197876 => 1s
‘datasets-without-resources’: 257.1773238182068 => 5m
‘publisher-resources’: 1495.1098330020905 => 25m
‘app-dataset-theme-report’: 2.033921003341675, 
‘app-dataset-report’: 4.2399139404296875
’site-usage-publisher’: 29.7936429977417
```

**Comment by rossjones** [comment]
Have modified the reports command to log how long each takes in case for some reason it is different in production (when the system is potentially under load, or perhaps problems with drupal).  Deployed to prod2 - will run full reports there just to ensure there is no breakage.
