### ISSUE TITLE
Remove data_dict from API response

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#213]
When calling the package_show API, it returns all of the same data in a data_dict key (this is the validated data that we use elsewhere) - it just clogs up the response, perhaps we could remove it?

**Comment by davidread** [comment]
Agreed that we don't need to return it. It does need to be stored in the SOLR record though, since its a cache. Do see if you can sort this out - I'm not sure how we have managed to be different to core CKAN in this respect.

**Comment by davidread** [comment]
I cherry-picked https://github.com/ckan/ckan/commit/595d0583d82 and have started a reindex.

Looks good e.g. https://data.gov.uk/api/action/package_show?id=1983-north-east-irish-sea-groundfish-survey-catch-data--silver-star-series
