### ISSUE TITLE
Add redirect for any traffic coming to our site that isn't data.gov.uk

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#219]
For instance www.contractsfinder.co.uk is pointing at us because the old hostnames are pointing at our main server, but it's not getting redirected to data.gov.uk. This is bad for our SEO.

**Comment by rossjones** [comment]
Is this done now?  That URL gets directed to https://data.gov.uk/data/contracts-finder-archive/

**Comment by morty** [comment]
Yes, I've tweeked the Nginx config and I think it does the right thing now.
