### ISSUE TITLE
Sensible default for publisher when adding a new dataset

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#233]
If you click on "Add a new dataset" link on the publishers page it should default to that publisher.

If you are only assigned as admin/editor to one publisher then it should default to that publisher no matter how you get to the new dataset page.

**Comment by davidread** [comment]
> If you click on "Add a new dataset" link on the publishers page it should default to that publisher.

This has now been fixed by https://github.com/datagovuk/ckanext-dgu/pull/297

> If you are only assigned as admin/editor to one publisher then it should default to that publisher no matter how you get to the new dataset page.

This wasn't done, as discussed here: https://github.com/datagovuk/ckanext-dgu/pull/297#issuecomment-169041908
