### ISSUE TITLE
If resource doesn't have a format use the one from QA

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#260]
Currently the dataset page just doesn't show a format meaning that it isn't immediately obvious that there is data available especially if the name of the resource isn't great (e.g. in a Gemini harvested resource).

**Comment by rossjones** [comment]
**Probably** involves having tasks.save_qa_result take a resource rather than a resource_id and then using that to check whether format is set before updating.

This may well trigger a new QA though, so should make sure that this doesn't cause a massive resource-guzzling cycle.

**Comment by sumothecat** [comment]
We have a record on your test env right now which may be a helpful example  https://test.data.gov.uk/dataset/habitat-point-records-from-1985-bmnh-kent-sussex-littoral-chalk-cliff-algal-survey. Thanks, Pete (JNCC).

**Comment by rossjones** [comment]
This should be fixed by https://github.com/datagovuk/ckanext-qa/pull/1 but will need further discussion about the consequences of doing this.

**Comment by davidread** [comment]
Just check if QA can't detect any format then it doesn't write it and get into a potentially infinite loop.

**Comment by rossjones** [comment]
I've pushed a new commit that's a little more defensive against pathological cases ( format = '   ' for instance).  I'll wait until test.dgu has finished running and then try it out on a few of those cases, but works locally for me without problems.

**Comment by rossjones** [comment]
This has finished running on test, and now the formats facet looks like the image below.  This has ruined my week :(

![datasets](https://cloud.githubusercontent.com/assets/118063/11711383/deaf3796-9f1d-11e5-8b53-832a5c28f344.jpg)
