### ISSUE TITLE
A simple way to list all existing content for a publisher

### ISSUE THREAD

**Issue by sumothecat** [datagovuk/ckanext-dgu#266]
We'd like an easy to generate a report that lists all the current JNCC content that exists on data.gov.uk. This needs to include the unique identifier, the title of the dataset and a link to the full on-line record. [also the licensing level – to allow us to track how many are OGL?]

**Comment by rossjones** [comment]
You might be able to work around this for now (admittedly it involves work) using the information in http://guidance.data.gov.uk/dgu_metadata_dumps.html

I imagine this would be reasonably scriptable (using cron/wget/jq).

**Comment by davidread** [comment]
We have a simple report of datasets here: https://data.gov.uk/data/report/publisher-resources/joint-nature-conservation-committee

But otherwise, what Ross said - use the dumps and if the CSV dump doesn't have what you want, extract the fields you want from the JSON dump.

**Comment by sumothecat** [comment]
Thank you both. The CSV dump looks good. 

Actually, if you added the (GU)ID to the web page report, you'd also have a web-based solution for non-techie data managers.

**Comment by davidread** [comment]
Yes, a PR would be welcome!
