### ISSUE TITLE
An efficient mechanism to “hide” multiple datasets

### ISSUE THREAD

**Issue by sumothecat** [datagovuk/ckanext-dgu#267]
There are a number of examples where potentially relatively large numbers of records have been published, but, as data management in the source organisation has evolved, the original divisions of "what is a dataset" are no longer appropriate. If the obsolete records need to remain persistent, ideally they should be "hidden" and no longer visible to general user searches.

The mechanism needs to allow for the fact that relatively large numbers of datasets need to be hidden in this way fairly efficiently (both for the provider and the data.gov team).

**Comment by rossjones** [comment]
Do you specifically mean hide as in 'make private', or using the soft-delete?

**Comment by davidread** [comment]
We use this issue repo for our internal work. This is an external feature request - please email it to us.
