### ISSUE TITLE
Publisher activity report: start/end dates

### ISSUE THREAD

**Issue by jacattell** [datagovuk/ckanext-dgu#270]
The [publisher activity report](https://data.gov.uk/data/report/publisher-activity/department-for-environment-food-and-rural-affairs?include_sub_organizations=1) shows activity in the current and last quarters. Defra need to specific start/end dates and for the outputted report to include the type of licence and the star rating for each dataset.

**Comment by rossjones** [comment]
This report isn't dynamic, it's generated in advance (because they take so long to generate for all publishers).  

This would probably have to be a new piece of work.  

My main worry would be if someone put in 2000 and 2015 as the bounds, as this would just regenerate the entire report again.  

Any thoughts on the best way to achieve this @davidread?

**Comment by davidread** [comment]
@jacattell Rather than specifying details of what is wanted, please will you explain the use case? What are they trying to achieve?

**Comment by DavidBuckster** [comment]
We would like to use the report to monitor our commitment to open data. So the initall part of that will be having a baseline for Defra and all sub-publishers published as under OGL as at 25th June 2015. plus management information going forwards.

**Comment by davidread** [comment]
Ok, tracking creation of datasets on data.gov.uk is easier than tracking which were updated on data.gov.uk. How about showing a number of datasets over time? Or a way to get a CSV of datasets on a particular date?

**Comment by DavidBuckster** [comment]
Creation is key, though I can see a need to know if we changed it to OGL so updated will become necessary in time. Number of data sets over time will be nice, and save writing them down, but know that could be complicated and new. For the immediate need if you can point me at the CSV of data sets on a particular date that would be a helpful start. (it's been a while)

**Comment by davidread** [comment]
Ok it sounds like what you need can be obtained from our daily dumps: https://data.gov.uk/dataset/data_gov_uk-datasets

For any date, from the CSV you can see all the datasets from Defra and is sub-publishers, and can see which were OGL or not.

For more tips in using these dumps see: http://guidance.data.gov.uk/dgu_metadata_dumps.html

I'm closing this as I think this is a reasonable solution, but reopen if you are missing anything.
