### ISSUE TITLE
CCZero licence missing from Data Package JSON

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#278]
https://data.gov.uk/dataset/the-linked-open-british-national-bibliography

has CC Zero licence. However the package doesn't have it:

https://data.gov.uk/dataset/the-linked-open-british-national-bibliography/datapackage.json

I guess that CCZero isn't in the licence map. However this is one of the 5 licences in our dataset form drop-down list, so really should work.

**Comment by davidread** [comment]
Please do deploy and update the data package for https://data.gov.uk/dataset/the-linked-open-british-national-bibliography so I can feed back to them that it is done

**Comment by morty** [comment]
OK, that data package has now been updated and shows the correct license.

**Comment by davidread** [comment]
Great, I'll let them know
