### ISSUE TITLE
Issues show username, not fullname

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#279]
We normally use fullname for display, because the username is used for the Drupal identifier.

We should change the templates to use the fullname rather than username. See https://data.gov.uk/dataset/clinical-commissioning-groups/issues/1 for example.

**Comment by davidread** [comment]
We should probably also change the helper function to link to /user/x (drupal) rather than /data/user/x (ckan).

**Comment by morty** [comment]
@davidread it looks like dgu_linked_user does link to the Drupal page for normal users, but to the CKAN page for sysadmins etc.

I will change it so it always links to the Drupal page.

**Comment by davidread** [comment]
Ah, cool
