### ISSUE TITLE
Jinjafication of extensions

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#294]

**Comment by rossjones** [comment]
Conversion of extensions to use jinja

* [ ] ckanext-harvest
* [ ] ckanext-spatial
* [ ] ckanext-os 
* [ ] ckanext-ga-report
* [ ] ckanext-dgu-local
* [ ] ckanext-qa

**Comment by davidread** [comment]
All PRs merged and deployed.

Some remaining bits in ckanext-dgu, to be covered in https://github.com/datagovuk/ckanext-dgu/issues/313
