### ISSUE TITLE
Issue shows sysadmin user

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#299]
When logged-out, the user who raised this issue shows as 'user_d102361' and links to https://data.gov.uk/user/user_d102361 but I think this should say 'system administrator'. Is this because a deployment of a fix needs doing on live?

https://data.gov.uk/dataset/clinical-commissioning-groups

**Comment by rossjones** [comment]
This is installed on test, should be good to go.

**Comment by rossjones** [comment]
Deployed to live.
