### ISSUE TITLE
Issue bullets should instead show horizontally

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#300]
The three bullets when viewing an issue on the dataset page:
<img width="350" alt="screen shot 2016-01-06 at 18 17 22" src="https://cloud.githubusercontent.com/assets/307612/12172079/8761c6ae-b546-11e5-84a9-4afd480b5267.png">
should instead show as three items side-by-side, as in the main ckanext-issues CSS:
<img width="949" alt="screen shot 2016-01-07 at 14 34 00" src="https://cloud.githubusercontent.com/assets/307612/12172941/ce0becf6-b54b-11e5-8b73-b8f82fcf92a0.png">

**Comment by morty** [comment]
This was because grunt hadn't been run after the deploy.
