### ISSUE TITLE
Search tips

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#308]
Given that we're enabling SOLR search syntax (#306) we could help power users by providing some pointers on using it for advanced search.

Near the search box we could have a link, e.g. "?", "Advanced" or "Advanced Search". That displays some really quick help. I suggest something along these lines:

* `"armed forces" expenses` - search for exact phrases by putting quote marks around them
* `primary school -care` `age NOT "cultural identity"` - exclude words or quoted phrases by using a minus sign or NOT
* `primary OR secondary school` - use 'OR' to allow alternatives (the default is to 'AND' all of the terms)
* "publisher: cabinet-office res_format: CSV" - search only in a particular field. (Lets list all the useful fields from our SOLR schema)

For more detail of the syntax, consult:
* https://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html

For other tips on searching see:
* http://guidance.data.gov.uk/finding_data.html
* http://guidance.data.gov.uk/api.html#searching

**Comment by davidread** [comment]
Moved from #312 

> AA suggests 'a line under the bar saying search tips which popups up with boolean operators and examples'.
> 
> We should mock something up for prod2 for review before doing all of this.

**Comment by rossjones** [comment]
Deployed on test for checking...

**Comment by rossjones** [comment]
Make some changes and re-deployed to test.
