### ISSUE TITLE
Analyse nginx logs

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#314]
Suggest doing a trial on logit.io

**Comment by davidread** [comment]
Just note what you've learnt and close this

**Comment by morty** [comment]
I was able to send the Nginx logs to logit.io using Logstash forwarder.

Once they had set it up so that their Logstash was aware of Nginx log files I was able to see the logs in Kibana - but I'm not sure how we can use this information. The Nginx log files don't contain a lot of information.
