### ISSUE TITLE
Limit baiduspider

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#317]
Can we rate-limit baiduspider? e.g. in nginx

Baiduspider is by far our most active bot, accounting for 9% of the requests to DGU, whereas googlebot is about 1.5%.

It doesn't respect robots.txt 'crawl-delay'. I'd be tempted to ban it, but it's maybe safest to just slow it down.

**Comment by morty** [comment]
This seems to work well. I've deployed it on our test server.

```
http {
    map $http_user_agent $is_limited_bot {
        "~Baiduspider" 1;
        "~OtherSpider" 2;
        default "";
    }
    limit_req_zone  $is_limited_bot zone=botzone:10m   rate=30r/m;

    server {
        ...

        location / {
            ...

            limit_req zone=botzone burst=5;
        }
    }
}
```

Test with `curl -I http://example.com -A OtherSpider` and only one request per 2 seconds should be allowed.

**Comment by davidread** [comment]
Sounds good, do deploy to live

**Comment by morty** [comment]
Deployed on live.
