### ISSUE TITLE
QA complains about case of URL

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#364]
This is from https://data.gov.uk/dataset/trafford-local-election-candidates-2016/resource/0f5592ca-ae16-456c-b275-3f146d42a94e (since fixed)

<img width="300" alt="trafford_elections_page_-_resources" src="https://cloud.githubusercontent.com/assets/118063/14403474/43426bde-fe4f-11e5-9c3c-8d4766fc385f.png">

Appears to do a case-sensitive match and complain even though the url works in browsers.

**Comment by davidread** [comment]
Fixed in https://github.com/ckan/ckanext-archiver/commit/2fe624f3516f3028939d65419fe02063da2ed2cb
and deployed to prod2 & prod3.
