### ISSUE TITLE
Make 'download' button easier to find

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#376]
because we've had a few user comments that they can't find it

**Comment by davidread** [comment]
Consider using the Gmail-style download system, where mouse hover presents a set of options.

**Comment by rossjones** [comment]
Might it need to be a lot more obvious that that?  Perhaps we should change the drop down on the right to ONLY be the download (as with datapackages) and have the filename or icon on the left go to preview?

**Comment by diabulos** [comment]
worth a try

**Comment by davidread** [comment]
Latest version I'm playing with:
<img width="831" alt="screen shot 2016-04-15 at 18 16 55" src="https://cloud.githubusercontent.com/assets/307612/14569382/56aa64a6-0336-11e6-9c7f-b6bb2de773c0.png">

**Comment by rossjones** [comment]
Ross to test on IE.

**Comment by davidread** [comment]
I fixed it for IE8 - it doesn't do the vertical centring for that and earlier versions of IE:
<img width="418" alt="screen shot 2016-04-25 at 17 26 18" src="https://cloud.githubusercontent.com/assets/307612/14790878/3049a8a8-0b0b-11e6-9d74-44aef29c2c58.png">

**Comment by davidread** [comment]
Number of downloads is marginally higher since this was deployed:
<img width="1107" alt="screen shot 2016-05-05 at 14 53 46" src="https://cloud.githubusercontent.com/assets/307612/15045199/435a39e4-12d1-11e6-9132-a0a42f0a58dd.png">
(Was deployed on 26th April. I've marked 27th April)

Use of the cached data has certainly gone down (although note the vertical scale is very different to the previous graph):
<img width="1113" alt="screen shot 2016-05-05 at 14 53 12" src="https://cloud.githubusercontent.com/assets/307612/15045204/48bb37a8-12d1-11e6-84d0-913d7b7d7b35.png">
