### ISSUE TITLE
Organogram viz - Multiple top posts not showing

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#378]
e.g. ACAS	

https://test.data.gov.uk/ckan_publisher/14/edit	
http://reference.data.gov.uk/gov-structure/organogram/?pubbod=advisory-conciliation-and-arbitration-service&version=2012-09-30

30/09/2012

3 top-level posts show on the old viz, but new viz only shows one. All 3 posts report to 'XX'. It is invalid to have more than one, but I think we should try and show all 3 for existing datasets, as we did before.

**Comment by davidread** [comment]
This is more and more of a problem, having redone the tests on 3 publishers in: https://github.com/datagovuk/ckanext-dgu/issues/365

**Comment by ratajczak** [comment]
fixed on test.data.gov.uk
