### ISSUE TITLE
Organogram viz - Not enough detail in senior post details box

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#379]
Senior post details misses: "Certification Office" post misses out:
* [x] "Combined salary of reporting posts"
* [x] "Working time"
* [x] "Role"
* [x] "Notes"
* [x] "Profession"
* [x] "Email"
* [x] "Phone"
* [x] "Unit(s)"

**Comment by ratajczak** [comment]
@davidread: I've added "Role", "Notes", "Profession", "Email" and "Phone"
Unit(s) was already there.
This is deployed to test.data.gov.uk.

I can't see where I can find "Certification Office" and "Working time", are they in the spreadsheets?

I'm also not sure how to implement "Combined salary of reporting posts", I can see a spinning wheel on reference.data.gov.uk indicating that this is being calculated. Most of them return 0, do you know requirements for implementing this?

**Comment by davidread** [comment]
Ignore "Certification Office" - that was just the name of the role I was looking at at the time.

"Working time" is the "FTE" column. I think it is better to call it "FTE (as a fraction of a full time role)"

"Combined salary of reporting posts" - tbh I've ignored this field until now. I'll read up on it and get back to you.

**Comment by davidread** [comment]
"Combined salary of reporting posts"
* this is a column in the senior sheet
* example:
    * All British Museum posts have a value for it, apart from the (top) Director.
    * data/dgu/xls/british_museum-30-09-2013.xls
    * http://reference.data.gov.uk/gov-structure/organogram/?pubbod=british-museum
* There are a bunch of reasons why most of the posts have no value (0, '' or 'N/D'), but just display what is in the sheet.
* The reason there is a spinning wheel on the TSO system is because they partitioned this one bit of info to require a separate call of the Linked Data API, called "statistics". I don't know why they did this. The value displays for me today, but of course it is flakey.
* This column was blank for most of the 2011 sheets (all those in data/dgu/xls-from-triplestore), because I had not got round to this field in my scripts. However I've now implemented this now and I'm updating the sheets - I'll let you know when this is done on prod2.

**Comment by ratajczak** [comment]
Good to hear that you've figured it out.
So far I've added FTE and deployed to test server.
https://test.data.gov.uk/organogram/cabinet-office/2011-09-30

**Comment by davidread** [comment]
Thanks for adding "FTE" but can you change the label to "FTE (as a fraction of a full time role)"?

The "Combined salary of reporting posts" column is now populated in the 2011 sheets now too (on prod2:/home/co/organogram-data/data/dgu/xls-from-triplestore). Example:
* British Museum's "Director of Collections" is £9,600,000
* http://reference.data.gov.uk/gov-structure/organogram/?pubbod=british-museum&version=2011-03-31

You said "Unit" is displayed, but it's not actually in the information box as I think it should:
<img width="533" alt="screen shot 2016-09-01 at 18 08 34" src="https://cloud.githubusercontent.com/assets/307612/18176827/44971f7e-706f-11e6-8a69-7934bfc87af9.png">
In this example it is "Strategy & Private Office" but it only shows in the diagram, and it's not clear that it is the Unit. I think it would be helpful to have it explicitly labelled in the information box.

In fact, while you're in there, can you add "Name:" label for the name? It's really not clear when the name is "N/D" (i.e. not disclosed) to not say what is not disclosed

**Comment by ratajczak** [comment]
This is done and deployed to test.data.gov.uk

**Comment by davidread** [comment]
Thanks for adding the Name label and Unit field.

However the other label is still not right - you missed the "FTE" bit this time. Please change it again to exactly: "FTE (as a fraction of a full time role)"

**Comment by davidread** [comment]
All done now
