### ISSUE TITLE
Organogram viz - senior salary has not pound signs

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#382]
e.g. https://test.data.gov.uk/ckan_publisher/323/edit# I click on preview for "31 Mar 2012" and click on "Chair" and the salary shows as "55000 - 59999" not "£55,000 - £59,999". i.e. pound sign and thousands commas are missing, compared to the old organogram and indeed the junior posts.

**Comment by ratajczak** [comment]
fixed on test.data.gov.uk
