### ISSUE TITLE
Roll out "issues" feature with CO & DfT

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#391]

**Comment by rossjones** [comment]
Contact, explain issues, ensure they are configured to have the feature turned on.

**Comment by pigspamster** [comment]
give a month or so and ask for feedback form CO and DfT

**Comment by davidread** [comment]
CO and DfT enabled and admin/editors emailed.

I took off 6 CO editors who have left CO or requested to be taken off. Recorded these on a sheet: https://docs.google.com/spreadsheets/d/1iPw4f-V0L1OfAq4NFl9xHV4qzP_8ggSA3tdrBMeO3uY/edit
