### ISSUE TITLE
Redirect existing blog posts to gov.uk URLs

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#393]
Blogs are now on gov.uk, we should redirect our existing blog posts to the there from Drupal.

**Comment by davidread** [comment]
This looks to be done (today). @ratajczak can you confirm?

**Comment by ratajczak** [comment]
I canfirm that this has been done but I couldn't find several blogs on data.blog.gov.uk.
This report contains all details:
https://docs.google.com/spreadsheets/d/1X-hcj1ks5IZvDzLSpIOY3FuBouIHTMm5qz-txUoMnC0/pubhtml
