### ISSUE TITLE
DoH organogram not displaying

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#407]
https://test.data.gov.uk/organogram/department-of-health/2015-03-31
shows blank organogram viz.

JS error in the console: `organogram.js?o6k1zh:499 Uncaught TypeError: Cannot read property 'name' of undefined`

**Comment by ratajczak** [comment]
This is down to data quality in XLS file:
![image](https://cloud.githubusercontent.com/assets/785792/15027252/c4a1383c-123a-11e6-99de-99e83146c3a4.png)

"Sc-212" foreign key doesn't match "SC-212" primary key because of lower case "c".
We can fix the data in the XLS file but maybe we can transform these primary and foreign key columns to upper case during ETL process and make our system case insensitive for these keys?

**Comment by davidread** [comment]
By far the top priority has got to be to display the good data and ignore any bad lines.

We know there are problems and inconsistencies with the data, and it is a low priority to fix them. On the basis of one example, I don't think we should be making decisions about going case insensitive or making improvements to XLS files. There are so many little problems like this.

**Comment by ratajczak** [comment]
So how should we resolve this issue?
Did you mean to make our javascript to ignore case?

**Comment by davidread** [comment]
So when you come across a role like this that has a parent that doesn't match any roles, skip the role. That is seems to be what the existing triplestore does - you can see that this junior role "Not In Post" is not shown whereas the rest (with the correctly capitalized parent ID) do:
<img width="707" alt="screen shot 2016-06-14 at 17 55 29" src="https://cloud.githubusercontent.com/assets/307612/16051844/69d2f140-3259-11e6-9cb4-1d3155ede90f.png">

**Comment by ratajczak** [comment]
this is now fixed and deployed to prod2, junior roles with missing parents are not rendered

**Comment by davidread** [comment]
Great to hear about the fix. Still, I can't do any testing because because the test server doesn't have any of the organograms data loaded still - do you think you could load it asap?

**Comment by ratajczak** [comment]
I tested this:
https://test.data.gov.uk/organogram/department-of-health/2015-03-31
and it still works for me.

**Comment by davidread** [comment]
You're quite right, it works there.
