### ISSUE TITLE
Remove open data glossary

### ISSUE THREAD

**Issue by pigspamster** [datagovuk/ckanext-dgu#418]
@david is this with you? I have no dependencies noted against this, how straight forward will this be and any impact on other things?

**Comment by davidread** [comment]
I thought we agreed it would be archived first. And then it would be @ratajczak who did the removal.

**Comment by ratajczak** [comment]
I also remember that.
So far I've removed it on test server:
https://test.data.gov.uk/glossary
Are we going to archive it as  a dataset?

**Comment by davidread** [comment]
Agreed:

* Take it off the nav bar
* Create an 'archive' page which links to the glossary page (and other archived pages)
* Add banner on the glossary page to say 'This is an archive, will not be updated and may be removed in future.'

**Comment by davidread** [comment]
@diabulos raised this again today - are there any blockers to achieving this? I guess you can ignore the bit about creating an 'archive' page, but the other two still hold.

**Comment by ratajczak** [comment]
There are no blockers any more.
The bug with 'Add comment' links going to access denied page after disabling commenting is now fixed.
@diabulos should I take it off the nav bar and add this banner on live?
It will have to be taken of the nav bar on CKAN side too.

**Comment by davidread** [comment]
I've taken it off the ckan nav bar now. So it's the Drupal nav bar and banner remaining to do, all on test server.

**Comment by ratajczak** [comment]
This is done on test server

**Comment by davidread** [comment]
Can be removed now on live.

**Comment by ratajczak** [comment]
this is done and removed from navigation in Drupal, @davidread could you please remove it from interact menu on CKAN side?

**Comment by davidread** [comment]
This is done on the ckan side too now.

Hooray this is complete!
