### ISSUE TITLE
Search for mixed case words gives incorrect results

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-dgu#431]
Searching for "LiDAR" gives different results from searching for "lidar" or "LIDAR".

https://twitter.com/owenboswarva/status/737902441228849152

From a quick internet search it seems that this may be due to WordDelimiterFilterFactory using case transition to break words up. It has a parameter called splitOnCaseChange which could be turned off, but we would need to think about the consequences.

Are there any times when we would expect splitting on case transition would do the right thing?

**Comment by morty** [comment]
This would also be an issue for indexing. If there was a dataset which only mentions LiDAR and not a single case version of that word then it would not appear in the search results for "lidar".

**Comment by morty** [comment]
OK, having done a little experiment on the test server it seems that changing the `splitOnCaseChange` for indexing doesn't have an effect. Maybe it indexes both the unsplit and spit versions?

I created a dataset while it was set as `splitOnCaseChange="0"` that contained the word "LiDAR" and it still showed up in a search for "lidar".

**Comment by davidread** [comment]
I'm not sure why changing splitOnCaseChange didn't work, but I managed to tell WordDelimiterFilterFactory to leave 'protected words' in protwords.txt and added "LiDAR" to it and the query now works fine, returning 200 results instead of thousands (as it was searching for "li" too, which matched loads of datasets).
