### ISSUE TITLE
Adding new metadata fields into a dataset

### ISSUE THREAD

**Issue by zvetaM** [datagovuk/ckanext-dgu#440]
Hello. I've been following the guide at http://docs.ckan.org/en/latest/extensions/adding-custom-fields.html, but the added field does not show up even when creating a new dataset. I got the error "ValueError: More than one fallback IDatasetForm has been registered" and when I set the return value of def is_fallback(self) in plugin.py of my newly made ckanext to False, CKAN now runs, but the new field is nowhere to be seen. I've checked the documentation of ckanext-dgu, as well as source code, but to be honest, I am lost.

Can you please give me some tips on how to add custom fields to datasets, so that they actually show up in your datagovuk portal?

**Comment by davidread** [comment]
The data.gov.uk form was created before IDatasetForm came along, so doesn't use it. Instead if overwrites the routes to a custom controller - see DguForm in plugin.py

So to edit the form, the main files are in ckanext-dgu: dataset_form.py, edit_form.html, read.html, read_common.html
