### ISSUE TITLE
Get rid of blog index page

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#443]
Instead of seeing https://data.gov.uk/blog users should be redirected to https://data.blog.gov.uk/

(note it is not the open data section, but the wider data blog)

AA says make this change on live.

**Comment by ratajczak** [comment]
This is done on live, should 'All blogs' menu item stay in the navigation or should I remove it?

**Comment by davidread** [comment]
Great, AA asks that you change the menu item from 'All blogs' to 'Blogs'.

**Comment by ratajczak** [comment]
This is done on Drupal side

**Comment by davidread** [comment]
Done on CKAN.
