### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#448]
BIS and HMRC can't see icons, apparently due to their orgs' IE security settings disallowing downloading of fonts.

Suggest we replace a few key icons with images, to allow them to do key journey: add/edit dataset.

**Comment by davidread** [comment]
From this:
<img width="286" alt="screen shot 2016-07-12 at 16 12 04" src="https://cloud.githubusercontent.com/assets/307612/16772808/77c7e404-484d-11e6-9cbe-2c0d87f22f09.png">
to this:
<img width="266" alt="screen shot 2016-07-12 at 16 11 35" src="https://cloud.githubusercontent.com/assets/307612/16772798/72fba3d4-484d-11e6-8261-fa5fd1776c80.png">

Logged in:
<img width="344" alt="screen shot 2016-07-12 at 16 28 58" src="https://cloud.githubusercontent.com/assets/307612/16772900/c39a6186-484d-11e6-93c1-c5e6a3a2750e.png">


Mobile (iphone 6):
<img width="373" alt="screen shot 2016-07-12 at 16 28 01" src="https://cloud.githubusercontent.com/assets/307612/16772867/aa90b320-484d-11e6-9a06-7fc906fd0687.png">

Mobile + logged in:
<img width="375" alt="screen shot 2016-07-12 at 16 31 21" src="https://cloud.githubusercontent.com/assets/307612/16772995/1cc023a4-484e-11e6-96c3-6c6f5d9e65a3.png">
(If the screen is any smaller then the 'Publisher tools' button is not shown)

I also changed the Home page icon in the breadcrumbs to text:
<img width="151" alt="screen shot 2016-07-12 at 16 42 10" src="https://cloud.githubusercontent.com/assets/307612/16773368/9cd288d8-484f-11e6-83f9-b19438309194.png">

and changed the search 'magnifier' icons to be an image on the header, dataset search and publisher search (visually the same):

<img width="117" alt="screen shot 2016-07-12 at 16 43 09" src="https://cloud.githubusercontent.com/assets/307612/16773399/bdcfe666-484f-11e6-98ea-e539c25f3ec4.png">

This is all done on the CKAN side and deployed to [test](https://test.data.gov.uk/data/search). Passing to @ratajczak to work on the Drupal side.

**Comment by ratajczak** [comment]
I've partialy implemented on Drupal side and deployed to test:
https://test.data.gov.uk/contact
It looks the same for not logged in users but after logging in this top black toolbar is rendered by a Drupal module and the number of items is dynamic depending on permissions for accessing particular administration sections.
Without this administrators wouldn't be able to easily find for example 'Users' section which is used to manage user accounts, block offenders, add permissions for new administrators, etc.
I just wanted to double check if I should remove this functionality and replace it with custom version with only 'My content' link?

**Comment by davidread** [comment]
@ratajczak yes, I agree that for sysadmins, Drupal should have its own version of the toolbar. There might be a challenge fitting in the DGU logo on the left side, since I moved it up. I'll let you ponder what to do about this.

**Comment by ratajczak** [comment]
@davidread I've implemented this custom toolbar exactly like on CKAN side but it's being used conditionally only for most basic authenticated users (who comment, create forum topics, etc.).
All users with more than one role (administrators, editors, data publishers) get current Drupal toolbar instead.
These users will experience discrepancy when switching between Drupal and CKAN pages but I hope that's acceptable because implementing this dynamic menu on CKAN side is not trivial and requires another integration point.
This is deployed to test.data.gov.uk and can be tested with masquerade box at the very bottom of each Drupal page.

**Comment by davidread** [comment]
Publishers look like this on the current site:
<img width="958" alt="screen shot 2016-07-18 at 09 29 23" src="https://cloud.githubusercontent.com/assets/307612/16909378/3a49db42-4cca-11e6-8e99-4b91ea04c77c.png">
Why can't this be done in custom code?

I appreciate that our 10 sysadmins (Drupal: administrators) and 4 Drupal editors need the standard Drupal toolbar as it has lots of fancy stuff for managing Drupal pages and searching for users. However I don't see why we can't do the custom toolbar for the 1700 data publisher users, when they only have one extra static link for 'Manage my content'.

Also, on test.data.gov.uk if masquerade as "Suzanne McLaughlin" then no toolbar appears at all - is this a bug?

Also to do is the Publisher tools button.

**Comment by davidread** [comment]
@ratajczak Let's deploy Drupal and CKAN to live at the same time. Give me a call if you're ready to do it straight away, or suggest a time.

**Comment by ratajczak** [comment]
@davidread: would tonight around 7pm or later be feasible for you?

**Comment by davidread** [comment]
This is now deployed to live. I'll do some updates to the guidance in a new ticket: https://github.com/datagovuk/ckanext-dgu/issues/452
