### ISSUE TITLE
Organogram manage - "Due next" appears twice

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#453]
As of today (20th July) it is showing both September and next March's periods, both as "Due next". It doesn't make sense to have them both marked as being the one that is next.

<img width="954" alt="screen shot 2016-07-20 at 14 04 35" src="https://cloud.githubusercontent.com/assets/307612/16987216/0126bfd2-4e83-11e6-9b26-4b91e8871dd0.png">

I suggest you only show one "Due next" period in the future i.e. hide it next March until 30th September, when the September data becomes "Due now".

**Comment by ratajczak** [comment]
fixed on test.data.gov.uk

**Comment by davidread** [comment]
Great
