### ISSUE TITLE
Can't see role properties in organogram view

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#457]
e.g. https://test.data.gov.uk/organogram/cabinet-office/2013-09-30

Bugs: When you click on a role, there should be a box that pops up with the details (including salary) (c.f. http://reference.data.gov.uk/gov-structure/organogram/?dept=co )

(Split off from https://github.com/datagovuk/ckanext-dgu/issues/406 )

**Comment by ratajczak** [comment]
fixed on test.data.gov.uk
