### ISSUE TITLE
Adding a custom metadata field to search filters

### ISSUE THREAD

**Issue by zvetaM** [datagovuk/ckanext-dgu#461]
Hello,

using the tips you provided in the issue https://github.com/datagovuk/ckanext-dgu/issues/440 I have successfully created several metadata fields. One of these fields I would now like to add among the search filters on the left-hand side of the ckan search page (among Publisher, Theme, Resource format and others).

The field that I would like to add to search filters has several possible values, which are stored in a vocabulary that has been populated using the paster command that executes:
_existing = model.Vocabulary.by_name('podrocja')
        if not existing:
            result1 = tk.get_action('vocabulary_create')(
                data_dict={'name': 'podrocja', 'tags': [
                {'name': u'Energetika'},
                {'name': u'Finance in davki'},
               ...
                {'name': u'Vlada in javni sektor'},
                {'name': u'Zdravje'},
                {'name': u'Znanost in tehnologija'}
            ]})_

Now I would like to be able to filter dataset by these tags. I've been trying to figure my way around the source code (search_facets in helpers.py, facet_options in _dgu_jinja_utils.html, etc.) but yet again I came out clueless as to how things work and how I could even start.
Could you please give me some hints on how I could start and how things work?

Thank you very much.

**Comment by davidread** [comment]
Sounds like you are there with the vocabulary.

For creating a search facet, look at this example: https://github.com/datagovuk/ckanext-dgu/commit/134e2386369528c63f9653218b119f0fc97e9b93
You basically need to:
* add it to the pkg_dict which is indexed in solr i.e. in before_index().
* add it to the solr schema config/solr/schema-2.0-dgu.xml
* add it to the template - _dgu_jinja_utils.html

To install it:
* vim $CKAN_INI    # and to search.facets append "collections"
* sudo cp /vagrant/src/ckanext-dgu/config/solr/schema-2.0-dgu.xml /usr/share/solr/solr-4.3.1/example/solr/collection1/conf/schema.xml  # Or change "collection1" to "ckan" (I can't remember what the default is)
* sudo service jetty restart
* paster --plugin=ckan search-index rebuild -r
* sudo apache2ctl graceful

**Comment by zvetaM** [comment]
Hello,

thank you for your reply. Unfortunately, I am having problems...

In _plugin.py_ I have added `SearchIndexing.add_podrocje(pkg_dict)` to the end of _before_index(self,pkg_dict)_. The function _add_podrocje()_ is as following

```
def add_podrocje(cls, pkg_dict):
        pkg_dict['all_podrocje'] = []
        podrocje = helpers.get_pkg_dict_extra(pkg_dict, 'podrocje', default=None)
        if podrocje:
            if isinstance(podrocje, types.StringType):
                podrocje = unicode(podrocje)
        pkg_dict['all_podrocje'].append(podrocje)

        log.debug('Podrocje: %s', ' '.join(str(podrocje)))
```

When I run _paster --plugin=ckan search-index rebuild --config=/var/ckan/ckan.ini_ , I can see in output
`2016-08-09 14:15:46,301 DEBUG [ckanext.dgu.search_indexing] **Podrocje: N o n e**`

But the field _podrocje_ is populated in datasets and is successfully displayed also on the dataset summary page. If I understand correctly, _add_podrocje(cls, pkg_dict)_ is called for each dataset and since the value of podrocje is accessible in _edit_form.html_ and _helpers.py_, it should be accessible also here...
------------------------------------------------------------

In _dataset_form.py_ is the field _podrocje_ defined as
...
`'podrocje': [not_empty, unicode, convert_to_extras],`
...
`'podrocje': [convert_from_extras, ignore_missing],`
...

and in _helpers.py_ as

`'podrocje': {'label': u'Področje', 'value': pkg_extras.get('podrocje','')},`

**Comment by davidread** [comment]
I'm not sure helpers.get_pkg_dict_extra is right here. You might just be able to do pkg_dict.get('podrocje'). Best thing is to pprint the pkg_dict and see.

**Comment by zvetaM** [comment]
pkg_dict.get('podrocje') worked. When I moved the dataset's field value into pkg_extras, I assumed that I had to use a pkg_extra.get() or get_pkg_dict_extra() functions.

It now works. Thank you.
