### ISSUE TITLE
"Eliminated" post should not be shown in viz

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#463]
e.g. BBSRC Sept 2012 - click "CHIEF EXECUTIVE", "DEPUTY CHIEF EXECUTIVE AND CHIEF OPERATING OFFICER", "DIRECTOR, PEOPLE AND DEVELOPMENT" and it reveals "Eliminated" post.

You need to discard any senior post with name="Eliminated". These posts should not have any reports, but if they do, it is ok to lose them too.

Old:
<img width="451" alt="screen shot 2016-08-11 at 17 49 36" src="https://cloud.githubusercontent.com/assets/307612/17597049/16a72fd4-5fec-11e6-99bf-a4761c84e95f.png">
http://reference.data.gov.uk/gov-structure/organogram/?pubbod=biotechnology-and-biological-sciences-research-council&version=2012-09-30

New:
<img width="1146" alt="screen shot 2016-08-11 at 17 44 49" src="https://cloud.githubusercontent.com/assets/307612/17597039/0fb26dba-5fec-11e6-97ec-31823d3de0ec.png">
https://test.data.gov.uk/organogram/manage/biotechnology-and-biological-sciences-research-council#

**Comment by ratajczak** [comment]
Fixed on test.data.gov.uk
