### ISSUE TITLE
No toolbar shown for partial admins

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#467]
e.g. someone who has Drupal roles (example user A):

authenticated user, moderator, data request administrator, editor.

sees no toolbar when viewing Drupal pages.

<img width="1228" alt="screen shot 2016-08-23 at 11 36 26" src="https://cloud.githubusercontent.com/assets/307612/17889003/e308fdc2-6925-11e6-965c-bb99ed8126e1.png">

--

Same happens for example user B with roles:

authenticated user, data publisher, CKAN sysadmin, data request administrator, editor

--

This is probably because I added this bit of logic, based on my assumptions about when the Drupal admin toolbar would appear:

<?php $needs_admin_toolbar = ($user->uid == 1 || array_intersect(array('administrator', 'editor', 'blogger', 'data request administrator', 'moderator', 'CKAN sysadmin'), array_values($user->roles))) ?>

https://github.com/datagovuk/dgu_d7/blob/master/themes/custom/dguk/templates/page.tpl.php#L7

So I made it display the basic/custom Drupal toolbar if $needs_admin_toolbar is false. Clearly this needs the same logic as when you display the Drupal toolbar. Do you think you could sync these up? I don't mind which one changes for these rare cases of people who are more than just an authenticated user but less than an administrator.

**Comment by ratajczak** [comment]
This was caused by missing toolbar module permissions for some roles.
I just fixed it by adjusting permissions.
I tested as Antonio, a random authenticated user and a random data publisher.
