### ISSUE TITLE
Organograms - latest visual changes

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#479]
Pawel:
* [x] On organogram view page, show a link to /manage/organograms/xyz, if you are a publisher with permission to manage it.
* [x] When you log-in, flash message showing a link to /manage/organograms, if you are a publisher.
* [x] On /manage/organograms, add some intro text: "To manage the publication of organogram data, select the relevant publisher:"
* [x] Change permissions so that an editor can only manage organograms for the publisher he is assigned i.e. not those lower in the tree. (Admin still has permissions down the tree).
* [x] Show a spinner (or equivalent mouse pointer change) when you click "Sign-off", "Publish" or "Delete", while the page is reloading.
* [x] On the manage page, the "Upload" button must be disabled for a row if the date is in the future
* [x] On the manage page, The "Due next" row should not be shown until 7th June and 7th December (the day after the deadline for the previous periods)
* [x] "Sign-off" checkbox - move this column to just before the "Actions" column
* [x] "Sign-off" checkbox - add "Sign-off" text next to the checkbox (and remove the column title).
* [ ] "Sign-off" checkbox - consider changing it to a toggle button or something
* [x] Flash message "Data uploaded and validated successfully" when your Upload succeeds
* [x] Flash message "Data published successfully: [view the dataset]" when Publish works (instead of "Resource created").
* [x] Remove duplicate spinner that shows on the view organogram page.
* [x] Publisher drop-down - alphabetical order (at top-level and within each branch)
* [x] Upload page - disable the 'Upload' button until a file has been specified
* [x] Avoid the double reload on the manage page when you click 'Upload' or 'Delete'.
* [x] Remove "Manage" on the manage page /organogram/manage and /organogram/manage/xyz "Manage Organogram publication" -> "Organogram publication".
* [x] Change message when a publisher logs in: "Manage organograms" -> "Organogram publication"

David:
* [x] Publisher page, remove "Manage" in the link text
* [x] Old organogram datasets - work out how to keep links to really old data and how to remove them on launch.
* [x] Look into Eliminated post that displayed - Dft Sept 2012 Director of Corporate Finance
* [x] Test "delete button"
* [x] Check we can upload xlsx format

**Comment by davidread** [comment]
The high priority ones - for docs screenshots - are:
* the Sign-off checkbox (Pawel)
* "Manage" in the link text (David)

**Comment by davidread** [comment]
Pawel wrote:
> Sign-off change is deployed on test.data.gov.uk

Great

> Also the cursor now changes to 'wait' after clicking 'Sign off' and before the page gets reloaded.

The cursor is fine. However there seems to be two reloads now when you do an upload or delete - could you have affected these at all? Also those buttons have a blue spinner in the page - I wonder if using that is possible, instead of the cursor, as it would be more consistent?

**Comment by ratajczak** [comment]
These two reloads were always there, I'll see if I can improve that quickly.
I'll implement this blue spinner, good idea.

**Comment by davidread** [comment]
Also, on the upload page, can you disable the 'Upload' button until a file has been specified? I've added a checkbox for this above.

**Comment by ratajczak** [comment]
All my tasks are done apart from:
"Sign-off" checkbox - consider changing it to a toggle button or something

**Comment by davidread** [comment]
Loads of really good improvements here - super! Just a couple of things I spotted:

AA was keen that we use 'publication' instead of the word 'manage'. Lets keep it in the URL, but can you change it in these places:
* On the manage page itself /organogram/manage and /organogram/manage/xyz "Manage Organogram publication" -> "Organogram publication". (Although it is fine in the paragraph.)
* Message when a publisher logs: "Manage organograms" -> "Organogram publication"

> On the manage page, The "Due next" row should not be shown until 7th June and 7th December (the day after the deadline for the previous periods)

This doesn't seem to be implemented - probably a misunderstanding. I'm still seeing the "31 Mar 2017" period, but this whole row shouldn't show until 7th December. https://test.data.gov.uk/organogram/manage/cabinet-office

**Comment by davidread** [comment]
> Old organogram datasets - work out how to keep links to really old data and how to remove them on launch.

I've move this into a new ticket: https://github.com/datagovuk/ckanext-dgu/issues/484 as it can be tackled later.

**Comment by davidread** [comment]
> Look into Eliminated post that displayed - Dft Sept 2012 Director of Corporate Finance

This is indeed a bug, so I've moved it into a new ticket: https://github.com/datagovuk/ckanext-dgu/issues/485

**Comment by ratajczak** [comment]
I've fixed "Due next" and removed "Manage" from page and message titles.
I think that we can consider this issue as fixed and look at:
 "Sign-off" checkbox - consider changing it to a toggle button or something
later if we have time.

**Comment by davidread** [comment]
Agreed :)
