### ISSUE TITLE
Organograms - XLS not downloadable

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#480]
I get a 404 trying to download a particular XLS. Others work, but not this one for some reason:
https://test.data.gov.uk/sites/default/files/organogram/uploads/advisory_conciliation_and_arbitration_service-2011-09-30-organogram.xls

The link to it is on this page:
https://test.data.gov.uk/organogram/manage/advisory-conciliation-and-arbitration-service

**Comment by ratajczak** [comment]
These files should be served by the webserver, this request should not reach Drupal.
I've checked that the file exist in expected location and has normal permissions like other files:
/var/www/files/drupal/dgud7/organogram/uploads/advisory_conciliation_and_arbitration_service-2011-09-30-organogram.xls
Locally I can download this file normally so I suspect that this is some misconfiguration of prod2, @davidread what do you think? 
@davidread are

**Comment by davidread** [comment]
It seems to work today... Closing. I'll look out for it happening again.
