### ISSUE TITLE
Organograms - upload errors stack up

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#481]
If I upload an invalid organogram twice in a row, then the previous error displays as well as the current one. It's not getting dismissed for some reason.
<img width="530" alt="screen shot 2016-09-09 at 12 58 45" src="https://cloud.githubusercontent.com/assets/307612/18386209/576401de-768d-11e6-8bb9-54046350f6bb.png">

**Comment by ratajczak** [comment]
fixed and deployed
