### ISSUE TITLE
Organograms - publisher not added to drop-down on view page

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#483]
I published an organogram for "Business bank" which didn't previously have an organogram, but when I view the organogram, "Business bank" doesn't appear to be added to the "Public body" select box (should be under BIS) and also the first item is selected incorrectly. Is there a problem adding publishers to the list?

https://test.data.gov.uk/organogram/business-bank/2011-03-31

**Comment by davidread** [comment]
I found another one - ACAS (should also appear under BIS). We already had organogram data for it so the newness is not the problem.

https://test.data.gov.uk/organogram/advisory-conciliation-and-arbitration-service/2011-09-30

**Comment by ratajczak** [comment]
fixed and deployed
