### ISSUE TITLE
Organograms - Eliminated posts showing at top level

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#485]
On this organogram view, at the top level there are dozens of posts which should not show because their name is "Eliminated":
https://test.data.gov.uk/organogram/department-for-transport/2012-09-30
e.g. "Director of Corporate Finance"

You have code that tests ```post.Name != 'Eliminated'``` when building the tree but I think you need to that in here too when doing the top-level:
```
if (post['Reports to Senior Post'].toLowerCase() == 'xx') {
                    topLevel.push(tree.length - 1);
                }
```

**Comment by ratajczak** [comment]
You were quite right Dave. It's fixed and deployed.
