### ISSUE TITLE
Organograms - unpublished XLS files need adding now

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#488]
I recently added to [uploads_report_tidied.csv](https://github.com/datagovuk/organograms/blob/gh-pages/uploads_report_tidied.csv) details of XLS files that were still in the uploaded and signed-off states (we already had the published ones). Can these be put into the new system too? i.e. preserving their states? Publishers may well want to go back and publish these.

e.g. "Human Fertilisation and Embryology Authority" 30/09/2014 is "signed off" and should be listed here: https://test.data.gov.uk/organogram/manage/human-fertilisation-and-embryology-authority

**Comment by ratajczak** [comment]
That shouldn't be a problem, can you add these organograms and also status column to tso_combined.csv?
My upload script performs upload, sign off and publish operations one by one in this order.
I can check the state and skip some of these operations.

**Comment by davidread** [comment]
As you suggest, I've now added these files to tso_combined.csv and a state column.

**Comment by davidread** [comment]
This is now done
