### ISSUE TITLE
Organograms - Cancelled upload carries on anyway

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#489]
If I upload an organogram file, during the actual transfer of the file, I can press the Cancel button, which returns me to the manage page. However a few seconds later it refreshes the page and says "File uploaded" - it didn't cancel the upload after all.

Since these are big files, taking a while to upload, it is useful to have a cancel option. Can it be made to work? If it is too hard, let's disable the button on starting the upload.

**Comment by ratajczak** [comment]
fixed and deployed
