### ISSUE TITLE
Organograms - Enable Sept 2016 uploads now

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#490]
To be able for us to test the upload functionality, with the tightened up validation (which is only from 30 Sep 2016 period), @ratajczak can you enable uploads for the "30 Sep 2016" period now? Either change this one period, or if it's easier, allow uploads from the 14th of the month before the date (i.e. now).

**Comment by ratajczak** [comment]
done and deployed. I made Sep 2016 an exception which is always enabled
