### ISSUE TITLE
Organograms - "rnrn" instead of newline

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#492]
I created this dataset by manually publishing its first XLS:
https://test.data.gov.uk/dataset/organogram-walsall-healthcare-nhs-trust
however the new-line in the description/notes field is showing as "rnrn".

You fixed this escaping issue for your migration script here: https://github.com/datagovuk/ckanext-dgu/issues/404#issuecomment-225681494 but it looks like manually publishing still has the issue

**Comment by davidread** [comment]
This might be related to an error I'm seeing on the viz page:

> Warning: urlencode() expects parameter 1 to be string, array given in dgu_organogram_viz_form() (line 1256 of /var/www/drupal/dgud7/build_dgud7_64/profiles/dgu/modules/features/dgu_organogram/dgu_organogram.module).

<img width="859" alt="screen shot 2016-09-19 at 17 41 55" src="https://cloud.githubusercontent.com/assets/307612/18640498/64e476f8-7e90-11e6-87a4-c98ae06ca438.png">

**Comment by ratajczak** [comment]
This is fixed, I tested it here https://test.data.gov.uk/dataset/organogram-academics
