### ISSUE TITLE
Organograms - 'delete' broken

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#493]
If I try to delete an organogram I get this error message:
<img width="1150" alt="screen shot 2016-09-19 at 17 49 54" src="https://cloud.githubusercontent.com/assets/307612/18640799/9906248a-7e91-11e6-92e0-1e4123f1fec2.png">
On page: https://test.data.gov.uk/organogram/manage/walsall-healthcare-nhs-trust

**Comment by davidread** [comment]
And then on the next Drupal page this is a pop-up red box with errors:

```
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 175 of /var/www/drupal/dgud7/build_dgud7_64/includes/entity.inc).
Notice: Trying to get property of non-object in _dgu_organogram_generate_csv_files() (line 136 of /var/www/drupal/dgud7/build_dgud7_64/profiles/dgu/modules/features/dgu_organogram/dgu_organogram.module).
```

**Comment by ratajczak** [comment]
fixed and deployed
