### ISSUE TITLE
Organograms - can't go back when on the upload screen

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#495]
When you go to the upload screen, there is no way to change your mind and go back to the Organogram publication page. If you press the browser 'back' button it unhelpfully skips the Organogram publication page, but I guess this is due to the nature of the upload screen being like a modal dialog box. Perhaps the 'Cancel' button could be enabed (at least until you start the actual upload).
<img width="573" alt="screen shot 2016-09-20 at 10 43 38" src="https://cloud.githubusercontent.com/assets/307612/18665421/2071b898-7f1f-11e6-8b5c-7384d9bf85b8.png">

**Comment by ratajczak** [comment]
fixed and deployed
