### ISSUE TITLE
Organograms - state date always says "published"

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#499]
On the Organogram Publication page, if you hover over the state value it says "Published on ..." whether it is published or not. It need to be changed to "Uploaded on ..." or "Signed off on ..." when in those states.

In addition, the date appears to be when the migration happened, when it should always be the "publish_date" in tso_combined.csv (whichever state it is in). I suggest you put "not recorded" if those dates are blank.

**Comment by ratajczak** [comment]
fixed and deployed
