### ISSUE TITLE
Organograms - Duplicate junior CSV link

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#500]
In the tests with the British Library, the user was surprised to see the Junior CSV appearing twice in the dataset:
<img width="1148" alt="screen shot 2016-09-21 at 12 15 04" src="https://cloud.githubusercontent.com/assets/307612/18710977/c7ff887a-7fff-11e6-81d6-8fea7d6529d1.png">
https://test.data.gov.uk/dataset/organogram-the-british-library%402016-09-21T09%3A22%3A43.686454
This shouldn't be happening.

**Comment by ratajczak** [comment]
I was happening everywhere, also when I tested manually:
https://test.data.gov.uk/dataset/organogram-bromley-pct
I fixed it and tested here:
https://test.data.gov.uk/dataset/organogram-british-film-institute
