### ISSUE TITLE
Organograms - IE8 viz doesn't display

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#504]
No viz on IE8. "Error on page". We need a warning message as a bare minimum.
<img width="1309" alt="screen shot 2016-09-23 at 14 07 28" src="https://cloud.githubusercontent.com/assets/307612/18786710/3a0c79f8-8197-11e6-99a0-6ba18d48201a.png">

Example link: https://test.data.gov.uk/organogram/cabinet-office

**Comment by davidread** [comment]
On the main viz page there is no error, just blank.
<img width="1309" alt="screen shot 2016-09-23 at 14 10 20" src="https://cloud.githubusercontent.com/assets/307612/18786772/8837c65a-8197-11e6-90e6-5b9e9a41ad57.png">

**Comment by davidread** [comment]
Here is the error, as shown in IE11 but running developer tools and pretending to be IE8:
<img width="1370" alt="screen shot 2016-09-23 at 14 22 07" src="https://cloud.githubusercontent.com/assets/307612/18787093/379022e0-8199-11e6-8421-ab2387066c04.png">

**Comment by davidread** [comment]
@maxf are you able to track this down, since Pawel has not had a chance to do this?

If you spot the fix in the browser, I can try hacking the change onto the file on the server.

**Comment by davidread** [comment]
Ah sorry @maxf - my error. Pawel put an update in an email and I missed it til now.

**Comment by davidread** [comment]
Pawel said:
> this error is in JIT library, unfortunately we are using the newest version.
> I'm guessing that it's not compatible with IE8 out of the box, maybe some additional library is needed.
> I couldn't find anything useful by searching this for error message in google.
> Should I add IE <= 8 message about preview and view functions not working?

Yes, please add a message about IE <=8 in place of the diagram on each page.

**Comment by ratajczak** [comment]
I added a message for IE <=8, please let me know if I should change wording for preview:
https://github.com/datagovuk/dgu_d7/pull/518/commits/ea95ddc959258bcd66bc4c45c216660e30d89bfc#diff-ea4b25db60251554416c018de9244e89R727
and view:
https://github.com/datagovuk/dgu_d7/pull/518/commits/ea95ddc959258bcd66bc4c45c216660e30d89bfc#diff-ea4b25db60251554416c018de9244e89R835

**Comment by davidread** [comment]
How about:

Unsupported browser. Requires Internet Explorer 9 or newer,
or Chrome, Firefox, etc.

**Comment by ratajczak** [comment]
I pushed this change live.
I traced this issue down to missing canvas element.
I think that I can fix this if it's worth supporting these browsers.

**Comment by davidread** [comment]
Yes, if it's easy...! I'm sure there will be departments that appreciate that, being stuck on IE8.

BTW it is displaying the message also for IE10 :( I guess it's this test:

    $.browser.version.substr(0,1)<9

There is a suggestion of how to cope with this problem here: http://stackoverflow.com/a/4226334/1512326

**Comment by ratajczak** [comment]
Thanks Dave, for now I've fixed IE10 issue following this suggestion:
https://github.com/datagovuk/dgu_d7/pull/521/commits/b352adae6ab8ad69a22022fbd7583a539ed855ac
could you please double check if it's fine now?

**Comment by davidread** [comment]
Yes that's great
