### ISSUE TITLE
Organograms - IE9&10 viz role details error

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#505]
When I click on a role there is an error and the details box doesn't pop up.

<img width="1370" alt="screen shot 2016-09-23 at 14 17 35" src="https://cloud.githubusercontent.com/assets/307612/18786994/ab74c04a-8198-11e6-9345-ade77162e68a.png">

Problem: IE9, IE10 (can't display it at all on IE8 currently due to https://github.com/datagovuk/ckanext-dgu/issues/504)
Works in: IE11/Edge

**Comment by ratajczak** [comment]
Fixed and deployed
