### ISSUE TITLE
Organograms - "Edit" should only appear for editors

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#511]
If I'm not logged in I see the "View Edit" links and I shouldn't
<img width="959" alt="screen shot 2016-09-30 at 11 27 44" src="https://cloud.githubusercontent.com/assets/307612/18988941/0ae61afc-8701-11e6-8507-38511c2f4af4.png">
https://test.data.gov.uk/organogram/cabinet-office

These should only appear if you are allowed to go to the publication page.

**Comment by ratajczak** [comment]
fixed and deployed to production
