### ISSUE TITLE
Organogram - launch problems on live

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#515]
* Can't access the backend. Logged in as davidread. When I go to e.g. https://data.gov.uk/organogram/manage/department-of-education I got "You are not authorized to access this page.". Same if I masquerade as a publisher user.
* "This section is currently under maintenance." needs removing e.g. on https://data.gov.uk/organogram/cabinet-office
* "Grade" is no longer displayed in the Senior post detail box. e.g. https://data.gov.uk/organogram/department-for-environment-food-and-rural-affairs/2014-09-30 Weird - it was there before: https://github.com/datagovuk/ckanext-dgu/issues/379#issuecomment-244148072
<img width="959" alt="screen shot 2016-10-02 at 20 11 01" src="https://cloud.githubusercontent.com/assets/307612/19023028/670441b0-88dc-11e6-8101-24d0670f7fae.png">

**Comment by ratajczak** [comment]
I've fixed permissions and removed maintenance message.
I'm looking at missing grade.

**Comment by ratajczak** [comment]
I just pushed fix for grade, this was needed:
https://github.com/datagovuk/dgu_d7/pull/520/commits/282f688180d1c8a3de2cd8d96d89ee4147e07e5c It looks like column name has changed in csv.
I can't remember fixing this before, am I right that this column name will be 'Grade (or equivalent)' in all generated csv files regardless of column name in xls?

**Comment by davidread** [comment]
Ah that'll be it. Yes I changed the etl to match the majority of the CSVs already out there. So they will all be 'Grade (or equivalent)'. Thanks for spotting that and fixing it.

Great, that's all the niggles sorted.
