### ISSUE TITLE
Organograms - sysadmin should see 'edit' button on a viz page

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#518]
Logged in as davidread, an administrator, I should see on all the viz pages an 'edit' link to go to the publication page. 

https://data.gov.uk/organogram/office-of-rail-and-road

However I'm only seeing it for the ones where I'm editor:

https://data.gov.uk/organogram/arts-council-england

I hope this is not a result of confusion over https://github.com/datagovuk/ckanext-dgu/issues/511 which is only to do with logged-out users not seeing 'edit'.

**Comment by ratajczak** [comment]
fixed and deployed
