### ISSUE TITLE
Organograms - Junior grade is not shown on the viz

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#521]
When viewing junior posts, the grade always shows as "undefined".
<img width="890" alt="screen shot 2016-10-07 at 14 28 02" src="https://cloud.githubusercontent.com/assets/307612/19191431/4fd8ad5c-8c9a-11e6-9854-fe91ace4ab47.png">

This was working before, but I think it got broke when you fixed the senior post grades:
https://github.com/datagovuk/ckanext-dgu/issues/515#issuecomment-250991258

Note: senior sheet has 'Grade (or equivalent)' but junior sheet just has 'Grade'.

**Comment by ratajczak** [comment]
fixed and deployed
