### ISSUE TITLE
Dataset-request

### ISSUE THREAD

**Issue by caduvieira** [datagovuk/ckanext-dgu#539]
Is the dataset-request (https://data.gov.uk/node/add/dataset-request) installed by this plugin? I would like to review and add this to another ckan instance.

Thanks

**Comment by rossjones** [comment]
@caduvieira Nope, it's part of the Drupal component which can be found at https://github.com/datagovuk/dgu_d7 - I believe it is https://github.com/datagovuk/dgu_d7/tree/master/modules/features/dgu_data_set_request
