### ISSUE TITLE
Organograms - Job share not showing in viz

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#541]
Where a post is a 'job share' between multiple people, only the first person's details are showing in the viz. e.g.
<img width="1144" alt="screen shot 2016-12-06 at 12 27 06" src="https://cloud.githubusercontent.com/assets/307612/20925542/8793ec5e-bbaf-11e6-945c-dbb0d54da276.png">

In the old viz all the people showed, so this needs fixing.

You can test this here:
https://test.data.gov.uk/organogram/manage/cabinet-office#
and the sample data is also available here:
https://github.com/datagovuk/organograms/blob/gh-pages/data/test-xls/sample1.xls?raw=true

**Comment by ratajczak** [comment]
I've fixed this and pushed live.
I couldn't find any real example of shared job to test on live but the same code is deployed to test server and can be tested here:
https://test.data.gov.uk/organogram/cabinet-office/2016-09-30

**Comment by davidread** [comment]
Thanks Pawel. It's good to see both people now, but it is problematic for their child nodes - they are now duplicated. The previous incarnation of organograms showed one box in the tree but both people in the job share in the role details pop-up for it. I think that would be preferable.

**Comment by ratajczak** [comment]
I should be able to change this, have you got a link to an example in old system or do you know how exactly this should be implemented?
I'm not sure if I should for example list these multiple values in a single field of this infobox separated with comas?

**Comment by davidread** [comment]
Finding a link is tough...

Maybe I can describe it though. The infobox was tall and had a scroll-bar. It had all the details of the first person and below it was all the details of the second person underneath. (And so on - there is no limit to job shares). Does that make sense?

**Comment by ratajczak** [comment]
Thanks Dave, I think that's clear. I'll try that.

**Comment by ratajczak** [comment]
I deployed this change here:
https://test.data.gov.uk/organogram/cabinet-office/2016-09-30
Is it ok?

**Comment by davidread** [comment]
Yes that's great. Do deploy to live if not done so already.

**Comment by ratajczak** [comment]
I deployed it live.
