### ISSUE TITLE
API/dumper for comments on datasets

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#553]
We need a way to get all the data out of Drupal. This could be a private API or an SQL command that returns it.

I'm aware we produced some web pages that provided them

eg https://data.gov.uk/comments/publisher/aa1e068a-23da-4563-b9c2-2cad272b663e

but we need this as data for migration.

**Comment by ratajczak** [comment]
You can get comments on datasets from this call:
https://data.gov.uk/services/rest/views/replies?entity_type=ckan_dataset
Where 'entity_id' is a primary key to a dataset in Drupal database.

I added an endpoint for mapping between CKAN and Drupal dataset ids: https://data.gov.uk/services/rest/datasets
So you can then get CKAN id or name having Drupal entity_id

**Comment by davidread** [comment]
Great, this works
