### ISSUE TITLE
API/dumper for organograms

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#556]
We need a way to get all the data out of Drupal. This could be a private API or an SQL command that returns it.

This gives basic details: https://test.data.gov.uk/services/rest/organogram

However the file details just returns a boolean:

https://test.data.gov.uk/services/rest/organogram/15291

I was expecting more - file download URL, signed-off/publish status, who/when it was uploaded & published etc.

**Comment by davidread** [comment]
All works apart from one: 7858 on live.

**Comment by davidread** [comment]
@ratajczak said he'd fixed this, but this still occurs with:

* https://test.data.gov.uk/services/rest/organogram/7858 
* https://test.data.gov.uk/services/rest/organogram/8380

**Comment by ratajczak** [comment]
This should be now fixed properly.

**Comment by davidread** [comment]
Thanks - all good now
