### ISSUE TITLE
Can't comment on datasets

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#563]
I can't comment on datasets any more - "not authorized"
<img width="1188" alt="screen shot 2017-01-31 at 13 58 37" src="https://cloud.githubusercontent.com/assets/307612/22467657/62fab5be-e7bd-11e6-92d4-a1f49d599316.png">

https://data.gov.uk/reply/add/13466/32/0
from https://data.gov.uk/dataset/road-accidents-safety-data

**Comment by ratajczak** [comment]
I've fixed that.
