### ISSUE TITLE
What's the license on the site assets?

### ISSUE THREAD

**Issue by CarlQLange** [datagovuk/ckanext-dgu#98]
Besides the logos (covered by the OGL), what's the license on the other general site assets (also stuff in shared-dgu-assets etc)? CC-BY?

Cheers!

**Comment by davidread** [comment]
Code & assets that have been generated as part of this project, that are in this repo, are OGL & AGPL licenced, as per the README. If you prefer CC-BY on specific assets, do ask and we'll check if we can.

I've also added licences for shared assets: https://github.com/datagovuk/shared_dguk_assets#copyright-and-licence
